# Generated by Django 4.2.6 on 2023-11-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forget_password_token',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
