# Generated by Django 4.2.6 on 2023-11-28 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_customuser_forget_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.process'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.subprocess'),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
