# Generated by Django 4.2.6 on 2023-11-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
