# Generated by Django 5.0.3 on 2024-04-02 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_quality_data_delete_quality_delete_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality_tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyst_name', models.CharField(max_length=100)),
                ('date_received', models.DateField()),
                ('transaction_number', models.CharField(max_length=50)),
                ('date_reviewed', models.DateField(blank=True, null=True)),
                ('process', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('sub_process', models.CharField(max_length=100)),
                ('tat', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('In Progress', 'In Progress'), ('Hold', 'Hold')], max_length=20)),
                ('query', models.CharField(choices=[('No Query', 'No Query'), ('Internal', 'Internal'), ('External', 'External')], max_length=20)),
                ('notes', models.TextField()),
                ('q1', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default='Pass', max_length=20)),
                ('q1_comment', models.TextField(default='')),
                ('q2', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default='Pass', max_length=20)),
                ('q2_comment', models.TextField(default='')),
                ('q3', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default='Pass', max_length=20)),
                ('q3_comment', models.TextField(default='')),
                ('q4_comment', models.TextField(default='')),
                ('q4_result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default='Pass', max_length=20)),
                ('q5', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default='Pass', max_length=20)),
                ('q5_comment', models.TextField(default='')),
                ('q6_comment', models.TextField(default='')),
                ('q6', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default='Pass', max_length=20)),
                ('q7_comment', models.TextField(default='')),
                ('q7_result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default='Pass', max_length=20)),
                ('q8', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default='Pass', max_length=20)),
                ('q8_comment', models.TextField(default='')),
                ('q9', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default='Pass', max_length=20)),
                ('q9_comment', models.TextField(default='')),
                ('q10', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default='Pass', max_length=20)),
                ('q10_comment', models.TextField(default='')),
                ('final_score', models.IntegerField(default='0')),
                ('pause1', models.DateTimeField(blank=True, null=True)),
                ('resume1', models.DateTimeField(blank=True, null=True)),
                ('pause2', models.DateTimeField(blank=True, null=True)),
                ('resume2', models.DateTimeField(blank=True, null=True)),
                ('pause3', models.DateTimeField(blank=True, null=True)),
                ('resume3', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('idle_time', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
