# Generated by Django 5.0.3 on 2024-04-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_production_q1_alter_production_q10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='q7',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='production',
            name='q9',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], max_length=20),
        ),
    ]
