# Generated by Django 5.0.3 on 2024-04-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_production_q7_alter_production_q9'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q10_comment',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q1_comment',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q2_comment',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q3_comment',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q4_comment',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q5_comment',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q6_comment',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q7_comment',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q8_comment',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q9',
        ),
        migrations.RemoveField(
            model_name='production',
            name='q9_comment',
        ),
    ]
