# Generated by Django 5.0.3 on 2024-04-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_quality_tracker_qstart_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quality_tracker',
        ),
    ]
