# Generated by Django 5.0.3 on 2024-04-09 15:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_delete_quality_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality_tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_number', models.CharField(blank=True, max_length=50, null=True)),
                ('qstart_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('qend_time', models.DateTimeField(blank=True, null=True)),
                ('q1_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default=None, max_length=20, null=True)),
                ('q1_comment', models.TextField(blank=True, default='', null=True)),
                ('q2_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default=None, max_length=20, null=True)),
                ('q2_comment', models.TextField(blank=True, default='', null=True)),
                ('q3_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default=None, max_length=20, null=True)),
                ('q3_comment', models.TextField(blank=True, default='', null=True)),
                ('q4_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default=None, max_length=20, null=True)),
                ('q4_comment', models.TextField(blank=True, default='', null=True)),
                ('q5_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default=None, max_length=20, null=True)),
                ('q5_comment', models.TextField(blank=True, default='', null=True)),
                ('q6_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default=None, max_length=20, null=True)),
                ('q6_comment', models.TextField(blank=True, default='', null=True)),
                ('q7_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default=None, max_length=20, null=True)),
                ('q7_comment', models.TextField(blank=True, default='', null=True)),
                ('q8_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default=None, max_length=20, null=True)),
                ('q8_comment', models.TextField(blank=True, default='', null=True)),
                ('q9_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default=None, max_length=20, null=True)),
                ('q9_comment', models.TextField(blank=True, default='', null=True)),
                ('q10_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'NA')], default=None, max_length=20, null=True)),
                ('q10_comment', models.TextField(blank=True, default='', null=True)),
                ('final_score', models.IntegerField(blank=True, null=True)),
                ('qpause1', models.DateTimeField(blank=True, null=True)),
                ('qresume1', models.DateTimeField(blank=True, null=True)),
                ('qpause2', models.DateTimeField(blank=True, null=True)),
                ('qresume2', models.DateTimeField(blank=True, null=True)),
                ('qpause3', models.DateTimeField(blank=True, null=True)),
                ('qresume3', models.DateTimeField(blank=True, null=True)),
                ('qduration', models.CharField(blank=True, max_length=20, null=True)),
                ('qidle_time', models.DurationField(blank=True, null=True)),
                ('Production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quality_tracker', to='main.production')),
            ],
            options={
                'ordering': ['auditor_name', 'transaction_number', 'qstart_time', 'qend_time', 'q1_result', 'q1_comment', 'q2_result', 'q2_comment', 'q3_result', 'q3_comment', 'q4_result', 'q4_comment', 'q5_result', 'q5_comment', 'q6_result', 'q6_comment', 'q7_result', 'q7_comment', 'q8_result', 'q8_comment', 'q9_result', 'q9_comment', 'q10_result', 'q10_comment', 'final_score'],
            },
        ),
    ]
