# Generated by Django 5.0.3 on 2024-04-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_quality_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='qc_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Complete', 'Complete')], default='Pending', max_length=20),
        ),
    ]
