# Generated by Django 5.0.3 on 2024-04-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_dataextraction_rename_notes_quality_tracker_q_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quality_tracker',
            old_name='q_notes',
            new_name='notes',
        ),
    ]
