# Generated by Django 5.0.3 on 2024-04-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_q_notes_quality_tracker_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quality_tracker',
            old_name='notes',
            new_name='q_notes',
        ),
    ]
