# Generated by Django 5.0.3 on 2024-04-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_quality_tracker_qdate_received_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataExtraction',
        ),
        migrations.RenameField(
            model_name='quality_tracker',
            old_name='q_notes',
            new_name='qnotes',
        ),
    ]
