# Generated by Django 5.0.3 on 2024-04-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_delete_dataextraction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
